-- ========================================
-- PASSO 1: Criar a tabela inventory
-- ========================================
CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================
-- PASSO 2: Ativar RLS (Row Level Security)
-- ========================================
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;

-- ========================================
-- PASSO 3: Criar política de acesso público
-- ========================================
CREATE POLICY "Public inventory is viewable by everyone"
  ON inventory FOR SELECT
  USING (true);

-- ========================================
-- PASSO 4: Inserir dados iniciais
-- ========================================
INSERT INTO inventory (product_id, product_name, quantity)
VALUES 
  ('1', 'Smartwatch Colmi P71', 3),
  ('2', 'Fone Lenovo GM2 Pro', 8),
  ('4', 'Pulseiras para Smartwatch 22mm', 12)
ON CONFLICT (product_id) DO NOTHING;

-- ========================================
-- PASSO 5: Verificar os dados inseridos
-- ========================================
SELECT id, product_id, product_name, quantity 
FROM inventory 
ORDER BY product_id;
