-- 1. Tabela de Produtos
create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null,
  old_price numeric,
  image_url text,
  description text,
  featured boolean default false,
  category text,
  specs text[]
);

-- 2. Tabela de Inventário (Estoque)
create table if not exists inventory (
  id bigint generated by default as identity primary key,
  product_id text not null unique,
  product_name text not null,
  quantity integer not null default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabela de Pedidos
create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_phone text not null,
  address text not null,
  payment_method text not null,
  total numeric not null,
  status text default 'pending', -- pending, sent, delivered
  items jsonb -- Guarda os itens comprados como JSON
);

-- 4. Segurança (RLS)
alter table products enable row level security;
alter table inventory enable row level security;
alter table orders enable row level security;

-- 5. Políticas de Acesso
-- Qualquer um pode ver os produtos
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

-- Qualquer um pode ver o inventário (estoque)
create policy "Public inventory is viewable by everyone"
  on inventory for select
  using ( true );

-- Qualquer um pode criar um pedido (Checkout)
create policy "Anyone can create an order"
  on orders for insert
  with check ( true );

-- 6. Dados Iniciais de Inventário
insert into inventory (product_id, product_name, quantity)
values 
  ('1', 'Smartwatch Colmi P71', 3),
  ('2', 'Fone Lenovo GM2 Pro', 8),
  ('4', 'Pulseiras para Smartwatch 22mm', 12)
on conflict (product_id) do nothing;

-- 7. Dados Iniciais de Produtos (Exemplo)
insert into products (title, price, old_price, image_url, description, featured)
select 'Smartwatch Colmi P71', 90.00, 120.00, 'https://placehold.co/600x600/2C3E36/FFFFFF?text=Colmi+P71', 'O campeão de vendas em Porto Velho. Resistente, elegante e com bateria para a semana toda.', true
where not exists (select 1 from products limit 1);

insert into products (title, price, old_price, image_url, description, featured)
select 'Fone Lenovo GM2 Pro', 80.00, 110.00, 'https://placehold.co/600x600/2C3E36/FFFFFF?text=Lenovo+GM2', 'Baixa latência para jogos e graves potentes para música. O fone definitivo.', false
where not exists (select 1 from products where title = 'Fone Lenovo GM2 Pro');
